In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df=pd.read_csv("C:/Users/admin/Downloads/cell_samples.csv")
df.head()

ID  Clump  UnifSize  UnifShape  MargAdh  SingEpiSize BareNuc  \
0  1000025      5         1          1        1            2       1   
1  1002945      5         4          4        5            7      10   
2  1015425      3         1          1        1            2       2   
3  1016277      6         8          8        1            3       4   
4  1017023      4         1          1        3            2       1   

   BlandChrom  NormNucl  Mit  Class  
0           3         1    1      2  
1           3         2    1      2  
2           3         1    1      2  
3           3         7    1      2  
4           3         1    1      2

In [4]:
#identifying missing values
import numpy as np

# replace "?" to NaN
df.replace("?", np.nan, inplace = True)
df.head(5)
missing_data = df.isnull()
missing_data.head(5)
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")    

ID
False    699
Name: ID, dtype: int64

Clump
False    699
Name: Clump, dtype: int64

UnifSize
False    699
Name: UnifSize, dtype: int64

UnifShape
False    699
Name: UnifShape, dtype: int64

MargAdh
False    699
Name: MargAdh, dtype: int64

SingEpiSize
False    699
Name: SingEpiSize, dtype: int64

BareNuc
False    683
True      16
Name: BareNuc, dtype: int64

BlandChrom
False    699
Name: BlandChrom, dtype: int64

NormNucl
False    699
Name: NormNucl, dtype: int64

Mit
False    699
Name: Mit, dtype: int64

Class
False    699
Name: Class, dtype: int64



In [9]:
avg_Bare=df["BareNuc"].astype("float").median(axis=0)
avg_Bare

1.0

In [11]:
df["BareNuc"].replace(np.NAN,avg_Bare,inplace=True)

In [14]:
#identifying missing values
import numpy as np

# replace "?" to NaN
df.replace("?", np.nan, inplace = True)
df.head(5)
missing_data = df.isnull()
missing_data.head(5)
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")    

ID
False    699
Name: ID, dtype: int64

Clump
False    699
Name: Clump, dtype: int64

UnifSize
False    699
Name: UnifSize, dtype: int64

UnifShape
False    699
Name: UnifShape, dtype: int64

MargAdh
False    699
Name: MargAdh, dtype: int64

SingEpiSize
False    699
Name: SingEpiSize, dtype: int64

BareNuc
False    699
Name: BareNuc, dtype: int64

BlandChrom
False    699
Name: BlandChrom, dtype: int64

NormNucl
False    699
Name: NormNucl, dtype: int64

Mit
False    699
Name: Mit, dtype: int64

Class
False    699
Name: Class, dtype: int64



In [18]:
df["BareNuc"]=df["BareNuc"].astype("int")
df.dtypes

ID             int64
Clump          int64
UnifSize       int64
UnifShape      int64
MargAdh        int64
SingEpiSize    int64
BareNuc        int32
BlandChrom     int64
NormNucl       int64
Mit            int64
Class          int64
dtype: object

In [20]:
df.columns

Index(['ID', 'Clump', 'UnifSize', 'UnifShape', 'MargAdh', 'SingEpiSize',
       'BareNuc', 'BlandChrom', 'NormNucl', 'Mit', 'Class'],
      dtype='object')

In [28]:
df.corr()["Class"][:-1]

ID            -0.080226
Clump          0.716001
UnifSize       0.817904
UnifShape      0.818934
MargAdh        0.696800
SingEpiSize    0.682785
BareNuc        0.818968
BlandChrom     0.756616
NormNucl       0.712244
Mit            0.423170
Name: Class, dtype: float64

In [33]:
a=df[['Clump', 'UnifSize', 'UnifShape', 'MargAdh', 'SingEpiSize',
       'BareNuc', 'BlandChrom', 'NormNucl']]
y=df["Class"]
a[0:5]

Clump  UnifSize  UnifShape  MargAdh  SingEpiSize  BareNuc  BlandChrom  \
0      5         1          1        1            2        1           3   
1      5         4          4        5            7       10           3   
2      3         1          1        1            2        2           3   
3      6         8          8        1            3        4           3   
4      4         1          1        3            2        1           3   

   NormNucl  
0         1  
1         2  
2         1  
3         7  
4         1

In [37]:
x=np.asarray(a)
x[0:5]
y=np.asarray(y)
y[0:5]

array([2, 2, 2, 2, 2], dtype=int64)

In [39]:
from sklearn import preprocessing
x = preprocessing.StandardScaler().fit(x).transform(x)
x[0:5]

array([[ 0.20693572, -0.69999505, -0.74329904, -0.63324716, -0.54956136,
        -0.68697917, -0.17966213, -0.61182504],
       [ 0.20693572,  0.28384518,  0.2668747 ,  0.76862067,  1.71010564,
         1.79966407, -0.17966213, -0.28411186],
       [-0.50386559, -0.69999505, -0.74329904, -0.63324716, -0.54956136,
        -0.41068547, -0.17966213, -0.61182504],
       [ 0.56233637,  1.59563215,  1.61377302, -0.63324716, -0.09762796,
         0.14190191, -0.17966213,  1.35445405],
       [-0.14846494, -0.69999505, -0.74329904,  0.06768675, -0.54956136,
        -0.68697917, -0.17966213, -0.61182504]])

In [43]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.30)
print(xtrain.shape,ytrain.shape)
print(xtest.shape,ytest.shape)

(489, 8) (489,)
(210, 8) (210,)


In [46]:
from sklearn import svm
sup = svm.SVC(kernel='rbf')
sup.fit(xtrain, ytrain) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [49]:
pred=sup.predict(xtest)
pred[0:5]

array([2, 4, 4, 4, 2], dtype=int64)

In [50]:
#evaluvation
from sklearn.metrics import confusion_matrix,jaccard_similarity_score,classification_report
jaccard_similarity_score(ytest,pred)

0.9619047619047619

In [53]:
confusion_matrix(ytest,pred,labels=[2,4])

array([[131,   5],
       [  3,  71]], dtype=int64)

In [55]:
print(classification_report(ytest,pred))

             precision    recall  f1-score   support

          2       0.98      0.96      0.97       136
          4       0.93      0.96      0.95        74

avg / total       0.96      0.96      0.96       210

